// translations.js
export const equipmentTranslations = {
	en: {
		equipmentList: [
			{
				name: "Tai Chi Wheel / Taiji Pushing / Push Hands",
				categories: ["multifunctional"],
				gif: ["1a", "1b"],
				icon: require("./../assets/images/icon/1.jpg"),
				pic: require("./../assets/images/equipment/1.jpg"),
				horizontalPic: require("./../assets/images/horizontal/1.jpg"),
				youtubeKey: "j8TWvoNzy_4",
				kinesiologyTip:
					"Rotating the Tai Chi wheel can improve the mobility and flexibility of the upper limb joints and muscles.\n\nThe squatting position can strengthen the muscles of the lower limbs.",
				ptTip:
					'Gentle joint movements help patients with "frozen shoulder" and shoulder arthritis maintain the range of motion of their shoulder joints and alleviate shoulder pain. When using the Tai Chi wheel, the use of force and range of rotation should not be too intense and should be kept within the range of motion that does not worsen the pain level.\n\nSemi-squat training benefits patients with hip and knee arthritis by strengthening the gluteus maximus and quadriceps muscles. It also helps seniors with poor balance to prevent falls. When performing a semi-squat, pay attention to the position of your back and legs. Keep your back as straight as possible, and ensure that your knees are aligned with your toes, and pointing straight ahead. Be cautious not to let your knees turn inward or stand with an out-toeing position.',
				otTip:
					"By engaging in the practice of rotating the dial with both hands, users can enhance the flexibility of their upper limb joints, making various everyday actions such as table wiping, object lifting, showering, and dressing significantly easier and more effortless.\n\nMoreover, practicing squat can strengthen the lower limb muscles and provides assistance for specific activities that involve transitioning from a seated position. For instance, standing up from a toilet seat becomes notably more manageable.",
				sound: "",
			},
			{
				name: "Upper Body Warm-Up",
				categories: ["wheelchair"],
				gif: [],
				icon: require("./../assets/images/icon/2.jpg"),
				pic: require("./../assets/images/equipment/2.jpg"),
				horizontalPic: require("./../assets/images/horizontal/2.jpg"),
				youtubeKey: "-s3fFWHcvus",
				kinesiologyTip:
					"This equipment aims to help users warm up their upper body. By continuously rotating the handlebars, it raises the body's temperature and increases the heart rate. The exercise movement also improves the mobility and flexibility of the upper limbs.",
				ptTip:
					"Continuous upper limb activity helps improve the mobility and flexibility of the upper limb joints and enhances cardiovascular function. Moderate-intensity aerobic exercise can help individuals with weaker cardiovascular functions, such as COVID-19 survivors, improve their heart and lung function. Aerobic exercise can also help control body weight and reduce the risk of developing hypertension, hyperlipidemia, and hyperglycemia, thereby lowering the risk of cardiovascular diseases. When performing aerobic exercise, it is important to maintain a level of exertion that feels comfortable but slightly challenging, allowing for continuous conversation with others while exercising.",
				otTip: "",
				sound: "",
			},
			{
				name: "Pull Up",
				categories: ["wheelchair"],
				gif: [],
				icon: require("./../assets/images/icon/3.jpg"),
				pic: require("./../assets/images/equipment/3.jpg"),
				horizontalPic: require("./../assets/images/horizontal/3.jpg"),
				youtubeKey: "k1sk8OpOpTs",
				kinesiologyTip: "This equipment assists the user in utilizing the strength of their upper body to lift themselves, thereby enhancing the strength of their upper body.",
				ptTip:
					"Pull-ups can help prevent shoulder pain caused by scapular displacement. However, before the back and shoulder muscles have adequate stability, it is essential to be cautious and control the intensity (lift-up height and speed) of the pull-up movement to avoid causing pain in the shoulders.",
				otTip: "",
				sound: "",
			},
			{
				name: "Upper Body Stretch & Strengthen",
				categories: ["wheelchair"],
				gif: ["4a", "4b"],
				icon: require("./../assets/images/icon/4.jpg"),
				pic: require("./../assets/images/equipment/4.jpg"),
				horizontalPic: require("./../assets/images/horizontal/4.jpg"),
				youtubeKey: "kR_2v56PhjY",
				kinesiologyTip: "By pushing the handlebars towards the center, this equipment can strengthen the muscles of the shoulders and arms of the user.",
				ptTip:
					"The movement of pushing the handlebars towards the center can help users to prevent shoulder pain caused by scapular displacement.\n\nBefore the upper limb and core muscles have adequate stability, be cautious of the speed of pushing and releasing the handlebars, in order to avoid causing pain in the shoulders.",
				otTip: "",
				sound: "4",
			},
			{
				name: "Calf Stretch",
				categories: ["multifunctional", "mobility"],
				gif: ["5a", "5b"],
				icon: require("./../assets/images/icon/5.jpg"),
				pic: require("./../assets/images/equipment/5.jpg"),
				horizontalPic: require("./../assets/images/horizontal/5.jpg"),
				youtubeKey: "98rD3sapCZM",
				kinesiologyTip:
					"This equipment has multiple functions and works on different parts of the body.\n\nLower limb Stretch: The inclined ramp can stretch and improve the flexibility of the hips, hamstrings, calves, and soles of the feet.",
				ptTip:
					'Using the inclined ramp can help patients with "plantar fasciitis" and "knee arthritis" increase the flexibility of the calf muscles and alleviate foot and knee joint pain. While on the inclined ramp, ensure the toes are pointed straight ahead and avoid standing with the feet turned outward.',
				otTip: "",
				sound: "5",
			},
			{
				name: "Climbing Shoulder Stretch",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/6.jpg"),
				pic: require("./../assets/images/equipment/6.jpg"),
				horizontalPic: require("./../assets/images/horizontal/6.jpg"),
				youtubeKey: "SCEqtpNFi54",
				kinesiologyTip:
					"This equipment has multiple functions and works on different parts of the body.\n\nClimbing Shoulder Stretch: By placing both hands on the side rails and the holes on the top, users can stretch the shoulders and the muscles of the back.",
				ptTip:
					'Gentle shoulder stretching can help patients with "frozen shoulder" and shoulder arthritis increase the flexibility of the shoulder muscles and reduce shoulder pain. During the stretch, the use of force and range of motion should not be excessive, and it should be within a range that does not exacerbate the pain.',
				otTip: "",
				sound: "",
			},
			{
				name: "Back Stretch",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/7.jpg"),
				pic: require("./../assets/images/equipment/7.jpg"),
				horizontalPic: require("./../assets/images/horizontal/7.jpg"),
				youtubeKey: "Wp3XgNfuWzo",
				kinesiologyTip:
					"This equipment has multiple functions and works on different parts of the body.\n\nBack Stretch: By holding the horizontal bar and pressing the upper body downwards, users can stretch the back muscles.",
				ptTip: "/",
				otTip: "",
				sound: "",
			},
			{
				name: "Push-Ups",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/8.jpg"),
				pic: require("./../assets/images/equipment/8.jpg"),
				horizontalPic: require("./../assets/images/horizontal/8.jpg"),
				youtubeKey: "TDDFgztPHhE",
				kinesiologyTip:
					"This equipment has multiple functions and works on different parts of the body.\n\nStanding Push-up: The standing push-up exercise helps to strengthen the muscles of the upper limbs of the users.",
				ptTip: "/",
				otTip: "",
				sound: "",
			},
			{
				name: "Twister",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/9.jpg"),
				pic: "",
				horizontalPic: require("./../assets/images/horizontal/9.jpg"),
				youtubeKey: "txqdaA0XgOk",
				kinesiologyTip:
					"By standing and twisting the torso from side to side, this equipment can help users to exercise the torso and lower limb muscles. With continuous use, it can also improve the respiratory system.",
				ptTip:
					"Gently twisting the torso helps patients with lower back pain to gain mobility and flexibility in their lower back. When using a waist-twisting machine, patients with low back pain should not perform the movements too quickly or with excessive range; it should be kept within a range that does not exacerbate pain. If there are symptoms of numbness or weakness in the lower limbs, consult physiotherapists before using the machine.",
				otTip: "",
				sound: "",
			},
			{
				name: "Rider",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/10.jpg"),
				pic: "",
				horizontalPic: require("./../assets/images/horizontal/10.jpg"),
				youtubeKey: "JC0vtfK5i5s",
				kinesiologyTip:
					"Pushing and pulling action can stretch and strengthen the muscles of the entire body. With continuous training, it can also enhance cardiorespiratory fitness.",
				ptTip:
					"Continuous upper limb activity helps improve the flexibility of the upper limb joints and enhances cardiorespiratory function. Moderate aerobic exercise can help individuals with weaker cardiorespiratory functions, such as COVID-19 survivors, improve their heart and lung function. Aerobic exercise can also help control body weight and reduce the risk of developing hypertension, hyperlipidemia, and hyperglycemia, thereby lowering the risk of cardiovascular diseases. During exercise, it's important to maintain a level of exertion that feels comfortable but slightly challenging, allowing continuous conversation with others while exercising.",
				otTip: "",
				sound: "",
			},
			{
				name: "Calf Stretch",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/11.jpg"),
				pic: "",
				horizontalPic: require("./../assets/images/horizontal/11.jpg"),
				youtubeKey: "bKl8JHH4ZHg",
				kinesiologyTip:
					"By elevating the forefoot higher than the heel, the calf muscles are stretched, which improve calf muscles’ flexibility and ankle mobility, and also enhances the overall functional ability.",
				ptTip:
					'Stepping on the inclined platform can help patients with "plantar fasciitis" and "knee arthritis" increase the flexibility of their calf muscles, thereby reducing pain in the foot and knee joints. When using the inclined platform, the toes should point straight ahead, and it\'s essential to avoid standing with the feet in an "out-toeing" position.',
				otTip: "",
				sound: "",
			},
			{
				name: "Balance",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/12.jpg"),
				pic: "",
				horizontalPic: "",
				youtubeKey: "JCf112TtyHk",
				kinesiologyTip: "Partial-lunge helps to strengthen the leg muscles, increase leg flexibility, and improve balance.",
				ptTip:
					'Partial-lunge can help patients with "plantar fasciitis" and "knee arthritis" increase the flexibility of the calf muscles, thereby reducing pain in the foot and knee joints. It can also strengthen the quadriceps in the front of the leg and help seniors with poor balance to prevent falls.\n\nWhen performing the partial-lunge, the front leg should be slightly bent, and the back leg should be straight. Pay attention to keep both the front and back foot pointing straight ahead, avoiding any out-toeing. Also, ensure that the front knee points straight ahead to avoid inward rotation.',
				otTip: "",
				sound: "",
			},
			{
				name: "Balance",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/13.jpg"),
				pic: "",
				horizontalPic: "",
				youtubeKey: "b9oG6eRfgJI",
				kinesiologyTip: "This equipment helps to enhance the user's perception of balance and increase the strength of the lower limb muscles.",
				ptTip:
					'Single-leg stance training can strengthen lower limb muscles and improve balance, which helps seniors prevent falls. When training balance, it is essential to prioritize safety and only attempt what is manageable. If balance ability is low, users do not need to release both hands during practice. Instead, they can start by using one hand for support or practice a "loose handgrip touching" technique. When balance improves, gradually release both hands to increase the difficulty level.',
				otTip: "",
				sound: "",
			},
			{
				name: "Back Strengthening",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/14.jpg"),
				pic: "",
				horizontalPic: "",
				youtubeKey: "NDCS4T-bbCA",
				kinesiologyTip: "The alternating movements of the arms and legs strengthen the back muscles and muscles along the spine.",
				ptTip:
					"The alternating movements of the arms and legs can help patients with lower back pain and sciatica to increase the stability of the spine and alleviate pain in the back and lower limbs. When performing this exercise, it is essential to avoid excessive range of motion while lifting the arms and legs and to slow down the movements. Focus on maintaining stability in the trunk and avoid arching back.\n\nDuring the practice, there should be no increase in pain in the lower back and lower limbs. If there is an increase in pain or symptoms such as numbness or weakness in the lower limbs, the exercise should be stopped immediately, and a physiotherapist should be consulted for further evaluation and guidance.",
				otTip: "",
				sound: "",
			},
			{
				name: "Standing Push-Up",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/15.jpg"),
				pic: "",
				horizontalPic: "",
				youtubeKey: "TgXPjEX1nnc",
				kinesiologyTip:
					"This equipment assists users to support their body weight to perform a standing push-up exercise. The exercise helps to strengthen the upper limb muscles.",
				ptTip: "",
				otTip: "",
				sound: "",
			},
			{
				name: "Bench Stepper",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/16.jpg"),
				pic: "",
				horizontalPic: "",
				youtubeKey: "-3G0jAm6Tho",
				kinesiologyTip: "Stepping exercises can strengthen the muscles of the lower limbs.",
				ptTip:
					'Stepping exercises can help patients with hip and knee arthritis to strengthen their gluteus maximus and quadriceps muscles, as well as assist seniors with poor balance in preventing falls. During step exercises, ensure that the knees align with the toes in a straight line, pointing forward, avoiding knee internal rotation, and "out-toeing" stance.\n\nPersistent step exercises also improve cardiovascular function. Moderate aerobic exercise benefits individuals with weak cardiorespiratory function, such as COVID-19 survivors, by enhancing their heart and lung capacity. Aerobic exercises also aid in weight management and reduce the risk of hypertension, hyperlipidemia, and hyperglycemia, lowering the risk of cardiovascular diseases. During exercise, maintain a level of exertion that feels comfortable but slightly challenging, allowing for continuous conversation with others while exercising.',
				otTip: "",
				sound: "",
			},
			{
				name: "Lower Body Stretch",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/17.jpg"),
				pic: "",
				horizontalPic: "",
				youtubeKey: "7F3qzQZqz5k",
				kinesiologyTip: "By placing one foot on the stool, the user can stretch the muscles at the back of the thigh, improving the flexibility of the legs.",
				ptTip:
					"This exercise helps to increase the flexibility of the muscles at the back of the thigh, providing relief for individuals with lower back pain and knee arthritis. When performing this exercise, ensure that the knee of the foot placed on the stool is fully extended and the toes are pointed upwards. Keep your back straight and slowly hinge from the hips, pressing the abdomen towards the thigh. You should feel a stretch sensation at the back of the thigh, but it should not be painful.",
				otTip: "",
				sound: "",
			},
			{
				name: "Fitness Bike / Cycling Machine",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/18.jpg"),
				pic: "",
				horizontalPic: "",
				youtubeKey: "15cShHBques",
				kinesiologyTip:
					"Generally, cycling is considered an aerobic exercise that can improve cardiorespiratory function. On top of improvement in cardiorespiratory functioning, increased leg movements can enhance the strength of the leg muscles and improve the mobility of the hip and knee joints.",
				ptTip:
					"Cycling is beneficial for individuals with hip and knee arthritis as it strengthens the lower limb muscles and enhances flexibility.\n\nFor those with more severe arthritis, choosing a bicycle with a higher seat can reduce the range of motion in the knee joint, thus minimizing knee joint wear and tear.\n\nRegular cycling strengthens the lower limbs, improves flexibility, and enhances cardiorespiratory function. Aerobic exercise can help individuals with weak cardiorespiratory functions, such as COVID-19 survivors, improve their heart and lung function. Aerobic exercise also aids in weight control and lowers the risk of developing hypertension, hyperlipidemia, and hyperglycemia, thereby reducing the risk of cardiovascular diseases. During exercise, it's important to maintain a level of exertion that feels comfortable but slightly challenging, allowing continuous conversation with others while exercising.",
				otTip: "",
				sound: "",
			},
			{
				name: "Airwalker / Health Walker",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/19.jpg"),
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "4_IDUrYSDdY",
				kinesiologyTip: "By simulating the motion of walking with alternate swings of the legs, users can exercise lower limbs and improve cardiorespiratory function.",
				ptTip:
					"Airwalker can be beneficial for patients with hip arthritis as it helps exercise the lower limbs, improving strength and flexibility. During walking, it is essential to keep the intensity and range within a level that does not exacerbate pain.\n\nExercising with an airwalker strengthens the lower limbs, and enhances cardiorespiratory function. Aerobic exercise can assist individuals with weak cardiorespiratory functions, such as COVID-19 survivors, in improving their heart and lung function. Aerobic exercise also aids in weight management and lowers the risk of hypertension, hyperlipidemia, and hyperglycemia, reducing the chances of cardiovascular diseases. During exercise, one should maintain an intensity that feels comfortable yet slightly challenging, allowing continuous conversation with others while exercising.",
				otTip: "",
				sound: "",
			},
			{
				name: "Shoulder stretch",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/20.jpg"),
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "oWBISdEwFyo",
				kinesiologyTip: "By rotating the wheels with both hands, you can enhance the flexibility and mobility of the upper limb joints and muscles.",
				ptTip:
					'Gentle joint movements can help individuals with "frozen shoulder" and shoulder arthritis in maintaining the range of motion in the shoulder joint and alleviate shoulder pain. When rotating the wheel, the rotational force and range should not be excessive, and it should be kept within a range that does not exacerbate the pain.',
				otTip: "",
				sound: "",
			},
			{
				name: "Pull-down Machine",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/21.jpg"),
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "TlTf9M84C94",
				kinesiologyTip: "By performing rope pulling exercises, users can enhance the flexibility of the upper limb joints.",
				ptTip:
					'Gentle joint movements can help individuals with "frozen shoulder" and shoulder arthritis maintain shoulder joint range of motion and flexibility. When performing rope pulling exercises, the hands can be positioned in front of or to the side of the body, but avoid pulling from behind the body. The force and range of motion during rope pulling should not be excessive, and it should remain within a range that does not exacerbate pain. If one hand feels weaker or painful, you can use the strength of the other hand to assist in the movement. To achieve stretching benefits, you can hold the position at the highest point within your comfortable range for a few seconds before slowly releasing.',
				otTip: "",
				sound: "",
			},
			{
				name: "Stepper",
				categories: [],
				gif: [],
				icon: require("./../assets/images/icon/22.jpg"),
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "ktO92CXy1WA",
				kinesiologyTip:
					"This equipment can help strengthen the lower limbs and improve body balance. Continuous training can also improve the functionality of the respiratory system.",
				ptTip:
					'Step exercises can assist individuals with hip and knee arthritis in building strength in their gluteal and quadriceps muscles. Additionally, it can aid older adults with balance issues in preventing falls. During step exercises, it\'s important to align the knees and toes in a straight line, pointing forward, and to avoid any inward rotation of the knee or standing with the feet in an "out-toeing" position.\n\nContinuous step exercises can also improve cardiorespiratory fitness. Aerobic exercise can help individuals with weak cardiorespiratory systems, such as those recovering from COVID-19, to enhance their heart and lung function. Aerobic exercise also helps control body weight and reduce the risk of hypertension, high cholesterol, and high blood sugar, ultimately lowering the risk of cardiovascular diseases. During exercise, one should aim for a level of intensity that feels slightly challenging but allows for continued conversation with others.',
				otTip: "",
				sound: "",
			},
			{
				name: "Back Massage",
				categories: [],
				gif: [],
				icon: "",
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "LWwOrOy300k",
				kinesiologyTip: "Using a roller with protruding points to massage the lower back helps to relax the muscles and improve the blood circulation in the lower back area.",
				ptTip:
					"Massage can help patients with low back pain and sciatica to relax their back muscles and relieve pain. During the massage, back-and-forth pressure, or targeted pressure can be applied to tense and sore areas. The massage pressure should be moderate, avoiding exacerbating pain in the lower back and limbs. If the pain increases or symptoms like leg numbness or weakness occur, stop using the massager and consult physiotherapists.",
				otTip: "",
				sound: "",
			},
			{
				name: "Joint Exerciser",
				categories: [],
				gif: [],
				icon: "",
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "qxQ6vmsCfLU",
				kinesiologyTip: "Upper Limb Exercise: Rotating the handlebar can improve the mobility of the upper limb joints.",
				ptTip:
					"Practicing the rotation of the handlebars helps maintain the mobility of the upper limb joints. When rotating the handlebars, there's no need to use excessive speed or force; it should be within a range that does not worsen the level of pain.",
				otTip: "",
				sound: "",
			},
			{
				name: "Joint Exerciser",
				categories: [],
				gif: [],
				icon: "",
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "Hb98QPvOXKc",
				kinesiologyTip:
					"Lower Limb Exercise: Legs lifting movements from the pedaling exercise can improve the strength of your leg muscles and the mobility of your knee and ankle joints.",
				ptTip:
					"Pedaling can help patients with hip and knee arthritis to improve the strength and flexibility of their lower limbs. During the training, the speed and force of pedaling should not be too vigorous and should be within a range that does not exacerbate the pain. If arthritis is severe, it is recommended to choose a higher or more backward seat position for the foot pedals to reduce wear and tear on the knee joints.",
				otTip: "",
				sound: "",
			},
			{
				name: "Leg Stretch",
				categories: [],
				gif: [],
				icon: "",
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "NJWSiegBkVo",
				kinesiologyTip:
					"Placing one foot on the horizontal bar allows the user to stretch the muscles in the lower back and the back of the thigh, thereby increasing flexibility in these areas.",
				ptTip:
					"The leg stretch can help patients with lower back pain and knee arthritis to increase the flexibility of the posterior thigh muscles, reducing pain in the lower back and knees. When using the leg stretch, ensure that one leg's knee is fully extended on the horizontal bar while maintaining a straight back. Slowly bend the hip, pressing the abdomen toward the thigh. You should feel a stretch sensation in the muscles at the back of the thigh. The sensation should not be painful.",
				otTip: "",
				sound: "",
			},
			{
				name: "Mini Health Walker",
				categories: [],
				gif: [],
				icon: "",
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "hT7V9PLA85w",
				kinesiologyTip: "The alternating swinging motion of both feet improves the mobility and flexibility of the knee and ankle joints and the associated muscles.",
				ptTip:
					"Swinging both feet can help patients with knee arthritis to improve their lower limb strength and flexibility. During the training, the swinging amplitude and intensity should not be too vigorous and should be kept within a range that does not worsen the pain. If the arthritis is severe, it is recommended to choose a higher seat or sit further away from the footrest to reduce the strain on the knee joints.",
				otTip: "",
				sound: "",
			},
			{
				name: "Arm Pedal",
				categories: [],
				gif: [],
				icon: "",
				pic: "",
				horizontalPic: "",
				detail: "",
				youtubeKey: "5c3H6xrTxxI",
				kinesiologyTip: "By rotating the handlebars, this equipment can improve the mobility and flexibility of the upper limb joints.",
				ptTip:
					"Rotating the handlebars helps to maintain the mobility and flexibility of the upper limb joints. When doing this exercise, avoid excessive speed and force, keeping within a range that won't exacerbate any pain.\n\nContinuous upper limb activity helps to improve the mobility of the upper limb joints, and enhances cardiorespiratory function. Moderate aerobic exercise can help individuals with weak cardiorespiratory functions, such as COVID-19 survivors to improve their heart and lung function. Aerobic exercise can also help control body weight and reduce the risk of developing hypertension, hyperlipidemia, and hyperglycemia, thereby lowering the risk of cardiovascular diseases. During exercise, it's important to maintain a level of exertion that feels comfortable but slightly challenging, allowing for continuous conversation with others while exercising.",
				otTip: "",
				sound: "",
			},
		],
	},
	zh: {
		item1: {
			name: "太極揉腿器/太極推手器",
			categories: ["Category A", "Category B"],
			gif: ["1a", "1b"],
			icon: require("./../assets/images/icon/1.jpg"),
			pic: require("./../assets/images/equipment/1.jpg"),
			horizontalPic: require("./../assets/images/horizontal/1.jpg"),
			youtubeKey: "j8TWvoNzy_4",
			kinesiologyTip: "使用這個健身設施時使用者要雙手轉動轉盤，這個動作能夠提升上肢關節的靈活性。 \n\n在轉動轉盤時使用者需維持下蹲的姿勢，此動作亦可以鍛煉到下肢的肌肉。",
			ptTip:
				"柔和的關節活動有助於「五十肩」和肩關節炎患者保持肩關節的活動幅度並減輕肩膊的疼痛。使用轉盤時，轉動的力度和幅度不能太大，應保持在一個不會加劇疼痛程度的範圍內。 \n\n半蹲的訓練有助於髖關節和膝關節炎患者強化臀大肌和股四頭肌，亦能幫助平衡力不足的長者預防跌倒。做半蹲的姿勢時，要注意背部和雙腿的位置。背部要盡量挺直，膝頭與腳尖應形成一直線，指向正前方，注意膝關節不要內旋，也不要「外八字腳」站立。",
			otTip: "",
			sound: "1",
		},
		item2: {
			name: "上身的熱身運動",
			categories: [],
			gif: [],
			icon: require("./../assets/images/icon/2.jpg"),
			pic: require("./../assets/images/equipment/2.jpg"),
			horizontalPic: require("./../assets/images/horizontal/2.jpg"),
			youtubeKey: "",
			kinesiologyTip: "這個健身設施主要幫助使用者的上半身進行熱身並活動上半身。\n\n使用者能透過持續轉動手柄，提升身體的温度和心跳率，以及上半身的活動能力。",
			ptTip:
				"持續的上肢活動除了能鍛煉上肢關節的靈活性，亦能增強心肺功能。適量的有氧運動能夠幫助新冠肺炎康復者等心肺功能較弱的人提升心肺功能。有氧運動亦能控制體重和降低三高（高血壓、高血脂、高血糖），減低患上心血管疾病的風險。做運動時，應保持在自己覺得輕鬆至有點困難的辛苦程度，運動時應該能夠與人持續對話的強度。",
			otTip: "",
			sound: "2",
		},
		item3: {
			name: "引體上升",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能協助使用者進行引體上升的訓練，以增強其上身的力量。",
			ptTip: "引體上升能夠預防肩胛骨移位所致的膊頭痛。在背部和肩膊肌肉未有足夠的穩定性前，做引體上升時要小心控制升降的高度和速度，盡量不要令肩膊出現疼痛。",
			otTip: "",
			sound: "",
		},
		item4: {
			name: "上身的伸展及強健鍛煉",
			categories: ["Category A", "Category B"],
			gif: ["4a", "4b"],
			icon: "",
			pic: "",
			horizontalPic: "",
			youtubeKey: "j8TWvoNzy_4",
			kinesiologyTip: "透過將這個健身器材的手柄推向中間，可以訓練使用者肩膊以及手臂的肌肉力量。",
			ptTip: "將手柄推向中間的動作能夠預防肩胛骨移位所致的膊頭痛。在上肢和核心肌肉未有足夠的穩定性前，推手柄的時侯要小心控制推和放的速度，盡量不要令肩膊出現疼痛。",
			otTip: "",
			sound: "4",
		},
		item5: {
			name: "全身伸展運動器",
			categories: ["Category C"],
			gif: ["5a", "5b"],
			icon: require("./../assets/images/icon/5.jpg"),
			pic: require("./../assets/images/equipment/5.jpg"),
			horizontalPic: require("./../assets/images/horizontal/5.jpg"),
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能讓使用者活動到不同部份的身體部位。\n\n下肢伸展：腳踏斜坡動作可以伸展到臀部、後腿、小腿以及足底，提高這部分的柔韌程度。\n\n",
			ptTip: "",
			otTip: "",
			sound: "5",
		},
		item6: {
			name: "全身伸展運動器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能讓使用者活動到不同部份的身體部位。\n\n肩關節伸展：透過擺放雙手在旁邊的板以及在板上的洞，可以伸展到膊頭，以及背部的肌肉。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item7: {
			name: "全身伸展運動器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能讓使用者活動到不同部份的身體部位。\n\n背部肌肉伸展：透過握住橫桿，上身向下壓的動作，可以伸展背部肌肉。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item8: {
			name: "全身伸展運動器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能讓使用者活動到不同部份的身體部位。\n\n站式掌上壓：透過進行站式掌上壓的訓練，可以增強上肢肌肉的力量。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item9: {
			name: "扭腰機",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "透過站立在轉盤及左右扭動軀幹，使用者能夠有效地鍛煉軀幹、下肢力量。如果持續重覆此運動，更可以增強呼吸系統的功能。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item10: {
			name: "健騎機",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "使用者可以利用兩臂推拉扶手作伸展運動及鍛煉全身肌肉。如果持續鍛煉，亦可以增強心肺功能。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item11: {
			name: "小腿伸展",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能讓使用者的前腳掌高於後腳跟。\n\n維持這個姿勢能令使用者的小腿後方肌肉伸展，增加小腿柔韌度以及足踝靈活性，亦可以增加小腿的活動能力。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item12: {
			name: "平衡鍛煉",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip:
				"這個健身設施能夠協助使用者維持半前蹲的姿勢進行訓練。\n\n透過進行半前蹲的動作，使用者可以訓練及增強其腿部肌肉的力量。並在增加腿部柔韌度的同時，提高使用者平衡力。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item13: {
			name: "平衡鍛煉",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能協助使用者維持單腳企的動作。\n\n進行單腳企訓練能增強使用者的平衡力感知，以及下肢肌肉的力量。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item14: {
			name: "強健背部",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "使用這個健身設施時需要使用者維持手腳交替的動作。\n\n這個動作能夠鍛煉使用者的背部肌肉，亦能強化其脊柱附近的肌肉。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item15: {
			name: "站立式臂伏撐",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施可以協助使用者透過上肢肌肉支撐身體重量，以完成站式掌上壓的動作。\n\n透過進行站式掌上壓訓練，可以增強使用者上肢肌肉的力量。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item16: {
			name: "踏級練習",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "透過使用這個健身設施進行踏級練習，使用者可以強化其下肢肌肉的力量。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item17: {
			name: "下身的伸展",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "透過將其中一隻腳放在櫈上，使用者可以利用這個健身設施伸展大腿後方的肌肉，並增加腿部的柔韌度。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item18: {
			name: "健體單車/腳部跑步器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip:
				"這個健身設施能讓使用者模擬進行踏單車運動。\n\n一般而言，踏單車是一種氧運動，可以增強心肺功能。另外，在踩單車嘅時候，提高腿部的動作可以增強腿部肌肉群的力量，髖關節以及膝關節的活動能力亦可以有所提升。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item19: {
			name: "離地漫步機/漫步機",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能夠模擬漫步的動作。\n\n透過雙腳交替擺動，使用者可以鍛煉下肢，並加強心肺功能。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item20: {
			name: "肩關節伸展",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "透過雙手轉動設施上轉輪，使用者可以增強其上肢關節的靈活性，以及肌肉的柔韌性。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item21: {
			name: "上肢伸展器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "透過左右手交替拉動設施上的拉桿或拉繩，可以增強使用者上肢關節的靈活度。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item22: {
			name: "踏步機",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施可以協助使用者進行踏步的動作。從而鍛煉其下肢以及身體的平衡感知。持續鍛煉亦可以增強呼吸系統功能。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item23: {
			name: "腰背按摩器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能協助使用者進行腰背的按摩。\n\n使用者能利用這個健身設施上的滾筒凸點按摩下腰部以放鬆相關肌肉，並增強腰背部的血液循環。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item24: {
			name: "關節健身架/綜合肌肉鍛煉器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "上肢運動：利用轉動扶手的動作，呢部器材能夠鍛煉上肢關節的靈活性。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item25: {
			name: "關節健身架/綜合肌肉鍛煉器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "下肢運動：交替踩腳踏的時候，提高腿部的動作可以增強腿部肌肉群的力量，同時亦能提升膝關節及足踝關節的活動能力。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item26: {
			name: "三位壓腿器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "透過將其中一隻腳放在橫桿上面，使用者可以伸展下腰及大腿後方的肌肉，增加相關部位的柔韌度。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item27: {
			name: "下肢伸展器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "這個健身設施能協助使用者進行雙腳交替擺動的動作，使其可以活動膝關以及腳踝關節，並增強相關肌群的柔靭性。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
		item28: {
			name: "手部鍛鍊器",
			categories: [],
			gif: [],
			icon: "",
			pic: "",
			horizontalPic: "",
			detail: "",
			youtubeKey: "",
			kinesiologyTip: "使用者能透過持續轉動手柄，提升上肢關節的靈活性。",
			ptTip: "",
			otTip: "",
			sound: "",
		},
	},
};
